config/routes.rb
Rails.application.routes.draw do
  root 'public#index'
  devise_for :users
  resources :users, only: [:show]
  resources :bands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :owner, inverse_of: :band, class_name: 'User', foreign_key: :owner_id
  include ImageUploader::Attachment(:image)
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :band, inverse_of: :owner, foreign_key: :owner_id, dependent: :destroy

  def full_name
    "#{self.firstname} #{self.lastname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :email, :password, :password_confirmation, :email_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, :email, :password, :password_confirmation, :current_password, :email_confirmation])
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: %i[ show edit update destroy ]

  # GET /bands or /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1 or /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands or /bands.json
  def create
    @band = Band.new(band_params)
    @band.owner = current_user

    respond_to do |format|
      if @band.save
        format.html { redirect_to band_url(@band), notice: "Band was successfully created." }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1 or /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to band_url(@band), notice: "Band was successfully updated." }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1 or /bands/1.json
  def destroy
    @band.destroy

    respond_to do |format|
      format.html { redirect_to bands_url, notice: "Band was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def band_params
      params.require(:band).permit(:name, :phonenumber, :bio, :image)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/_band.html.erb
<div class="xl:w-1/3 md:w-1/2 p-4" id="<%= dom_id band %>">
  <div class="border border-gray-300 p-6 rounded-lg">
    <% if band.image %>
      <%= image_tag band.image_url class: "object-cover object-center rounded mb-8 h-64 w-full", alt: band.name %>
    <% else %>
      <img alt="feature" class="object-cover object-center rounded mb-8 w-full" src="https://dummyimage.com/340x250/edf2f7/a5afbd">
    <% end %>
    <%= link_to band.name, band, class: "text-lg text-gray-900 font-bold title-font mb-2" %>
    <p class="leading-relaxed text-base"><%= band.bio %></p>
  </div>
</div>

app/views/bands/_form.html.erb
<%= form_with(model: band, class: "contents") do |form| %>
  <% if band.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
        <% band.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="md:flex mb-8">
    <%# <div class="md:w-1/3">
      <legend class="uppercase tracking-wide text-sm">Details</legend>
    </div> %>
    <div class="md:flex-1 mt-2 mb:mt-0 px-3">
      <div class="mb-4">
        <%= form.label :name, class: "block uppercase tracking-wide text-xs font-bold" %>
        <%= form.text_field :name, autofocus: true, class: "w-full shadow-inner p-4 border-0", placeholder: "Enter your Band's name." %>
      </div>
      <%#=
      <div class="md:flex mb-4">
        <div class="md:flex-1 md:pr-3">
          <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Street Address</label>
          <input class="w-full shadow-inner p-4 border-0" type="text" name="address_street" placeholder="555 Roadrunner Lane">
        </div>
        <div class="md:flex-1 md:pl-3">
          <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Building/Suite No.</label>
          <input class="w-full shadow-inner p-4 border-0" type="text" name="address_number" placeholder="#3">
        </div>
      </div>
      <div class="md:flex mb-4">
        <div class="md:flex-1 md:pr-3">
          <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Latitude</label>
          <input class="w-full shadow-inner p-4 border-0" type="text" name="lat" placeholder="30.0455542">
        </div>
        <div class="md:flex-1 md:pl-3">
          <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Longitude</label>
          <input class="w-full shadow-inner p-4 border-0" type="text" name="lon" placeholder="-99.1405168">
        </div>
      </div>
      %>
    </div>
  </div>
  <div class="md:flex mb-8">
    <%# <div class="md:w-1/3">
      <legend class="uppercase tracking-wide text-sm">Contact</legend>
    </div> %>
    <div class="md:flex-1 mt-2 mb:mt-0 px-3">
      <div class="mb-4">
        <%= form.label :phonenumber, class: "block uppercase tracking-wide text-xs font-bold" %>
        <%= form.text_field :phonenumber, class: "w-full shadow-inner p-4 border-0", placeholder: "(555) 555-5555" %>
      </div>
      <%#=
      <div class="mb-4">
        <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">URL</label>
        <input class="w-full shadow-inner p-4 border-0" type="url" name="url" placeholder="acme.co">
      </div>
      <div class="mb-4">
        <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Email</label>
        <input class="w-full shadow-inner p-4 border-0" type="email" name="email" placeholder="contact@acme.co">
      </div>
      %>
    </div>
  </div>
  <%#=
  <div class="md:flex">
    <div class="md:w-1/3">
      <legend class="uppercase tracking-wide text-sm">Social</legend>
    </div>
    <div class="md:flex-1 mt-2 mb:mt-0 md:px-3">
      <div class="md:flex mb-4">
        <div class="md:flex-1 md:pr-3">
          <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Facebook</label>
          <div class="w-full flex">
            <span class="text-xs py-4 px-2 bg-grey-light text-grey-dark">facebook.com/</span>
            <input class="flex-1 shadow-inner p-4 border-0" type="text" name="facebook" placeholder="acmeco">
          </div>
        </div>
        <div class="md:flex-1 md:pl-3 mt-2 md:mt-0">
          <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Twitter</label>
          <div class="w-full flex">
            <span class="text-xs py-4 px-2 bg-grey-light text-grey-dark">twitter.com/</span>
            <input class="flex-1 shadow-inner p-4 border-0" type="text" name="twitter" placeholder="acmeco">
          </div>
        </div>
      </div>
      <div class="md:flex mb-4">
        <div class="md:flex-1 md:pr-3">
          <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Instagram</label>
          <div class="w-full flex">
            <span class="text-xs py-4 px-2 bg-grey-light text-grey-dark">instagram.com/</span>
            <input class="flex-1 shadow-inner p-4 border-0" type="text" name="instagram" placeholder="acmeco">
          </div>
        </div>
        <div class="md:flex-1 md:pl-3 mt-2 md:mt-0">
          <label class="block uppercase tracking-wide text-charcoal-darker text-xs font-bold">Yelp</label>
          <div class="w-full flex">
            <span class="text-xs py-4 px-2 bg-grey-light text-grey-dark">yelp.com/</span>
            <input class="flex-1 shadow-inner p-4 border-0" type="text" name="yelp" placeholder="acmeco">
          </div>
        </div>
      </div>
    </div>
  </div>
  %>
  <div class="md:flex mb-6">
    <%# <div class="md:w-1/3">
      <legend class="uppercase tracking-wide text-sm">Description</legend>
    </div> %>
    <div class="md:flex-1 mt-2 mb:mt-0 px-3">
      <%= form.text_area :bio, class: "w-full shadow-inner p-4 border-0", placeholder: "Enter your Band's bio", rows: 6 %>
    </div>
  </div>
  <div class="md:flex mb-6">
    <%# <div class="md:w-1/3">
      <legend class="uppercase tracking-wide text-sm">Cover Image</legend>
    </div> %>
    <div class="md:flex-1 px-3 text-center">
      <div class="flex w-full items-center justify-center">
        <label class="flex flex-col items-center flex-shrink-0 px-3 py-3 bg-yellow-500 rounded-lg uppercase cursor-pointer hover:bg-yellow-600 hover:text-white">
          <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
          </svg>
          <span class="mt-2 text-base leading-normal">Add Cover Image</span>
          <%= image_tag form.object.image_url if form.object.cached_image_data %>
          <%#= form.hidden_field :image, value: form.object.cached_image_data %>
          <%= form.file_field :image, class: "opacity-0 absolute pin-x pin-y"%>
        </label>
      </div>
    </div>
  </div>
  <div class="md:flex mb-6 border border-t-1 border-b-0 border-x-0 border-cream-dark">
    <div class="md:flex px-3 text-center md:text-right">
      <%= link_to "Cancel", band, class: "bg-gray-100 hover:bg-gray-800 hover:text-white rounded mt-2 py-2 px-4 font-bold" %>
    </div>
    <div class="md:flex-1 px-3 text-center md:text-right">
      <%= form.submit class: "bg-purple-500 hover:bg-purple-800 text-white font-bold mt-2 py-2 px-4 rounded" %>
    </div>
  </div>
<% end %>

app/views/bands/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing band</h1>

  <%= render "form", band: @band %>
</div>

app/views/bands/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <section class="text-gray-700 body-font border-t border-gray-200">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-wrap -m-4">
        <% @bands.each do |band| %>
          <%= render "band", band: band %>
        <% end %>
      </div>
      <button class="flex mx-auto mt-16 text-white bg-purple-500 hover:bg-purple-800 text-white font-semibold border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">See More</button>
    </div>
  </section>
</div>

app/views/bands/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h2 class="text-center text-purple-400 font-bold text-2xl uppercase my-10">Fill out our form</h2>

  <%= render "form", band: @band %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents") do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Groups</h1>
    <%= link_to 'New group', new_group_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="groups" class="min-w-full">
    <%= render @groups %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Byo Beats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag 'icon.ico' %>
  </head>
  <body>
    <main class="bg-gray-50">
      <%= render "shared/nav" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </main>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="text-gray-700 body-font">
  <div class="border-t border-gray-200">
    <div class="container px-5 py-8 flex flex-wrap mx-auto items-center">
      <span class="inline-flex lg:ml-auto lg:mt-0 mt-6 w-full justify-center md:justify-start md:w-auto">
        <a class="text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
          </svg>
        </a>
      </span>
    </div>
  </div>
  <div class="bg-gray-200">
    <div class="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row">
      <p class="text-gray-500 text-sm text-center sm:text-left">© 2023
        <a href="https://www.byobeats.com.au" class="text-gray-600 ml-1" target="_blank" rel="noopener noreferrer">BYO BEATS</a>
      </p>
      <span class="sm:ml-auto sm:mt-0 mt-2 sm:w-auto w-full sm:text-left text-center text-gray-500 text-sm">Enamel pin tousled raclette tacos irony</span>
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="text-gray-700 body-font border-b border-gray-200">
  <div class="p-5 flex justify-between items-center">
    <%= link_to root_path, class: "flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" do %>
      <%= image_tag "byo_beats.png", class: "w-20 h-10 rounded-full cursor-pointer", alt: "logo" %>
      <span class="ml-3 text-xl">BYO BEATS .</span>
    <% end %>
    <!-- MOBILE NAV ICON -->
    <div class="md:hidden block absolute top-4 right-8 fixed">
      <button aria-label="navigation" type="button"  class="md:hidden text-gray-200 transition duration-300 focus:outline-none focus:text-white hover:text-white">
        <div id="bars" class="ml-4 w-8 h-8 inline-flex items-center justify-center text-gray-900 flex-shrink-0">
          <svg fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 5.25h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5"></path>
          </svg>
        </div>
      </button>
    </div>
    <!-- NAVIGATION - LARGE SCREENS -->
    <div class="hidden md:flex">
      <ul class="hidden md:flex">
        <% if user_signed_in? %>
          <% if current_user.band.present? %>
            <li class="text-lg pr-8">
              <%= link_to 'My Band', band_path(current_user.band), class: "transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500", style: "text-underline-offset: 8px;" %>
            </li>
          <% else %>
            <li class="text-lg pr-8 ">
              <%= link_to 'Register Your Band', new_band_path, class: "transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500", style: "text-underline-offset: 8px;" %>
            </li>
            <% end %>
          <li class="text-lg pr-8">
            <%= link_to 'My Gigs', '#', class: "transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500", style: "text-underline-offset: 8px;" %>
          </li>
        <% end %>

        <li class="text-lg pr-8"><a href="#" class="transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500" style="text-underline-offset: 8px;">Pricing</a></li>
        <li class="text-lg pr-8">
          <%= link_to 'Bands', bands_path, class: "transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500", style: "text-underline-offset: 8px;" %>
        </li>
      </ul>
    </div>

    <div class="hidden md:flex">
      <% if user_signed_in? %>
        <div class="flex md:space-x-6 items-center ml-auto">
          <%= link_to "#" do %>
            <div class="flex items-center mb-3">
              <div class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full text-purple flex-shrink-0">
                <svg fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75"></path>
                </svg>
              </div>
            </div>
          <% end %>
          <%= link_to user_path(current_user) do %>
            <div class="flex items-center mb-3">
              <div class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-purple-500 text-white flex-shrink-0">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                  <circle cx="12" cy="7" r="4"></circle>
                </svg>
              </div>
              <%= current_user.firstname.capitalize %>
            </div>
          <% end %>
          <%#= button_to "Log out", destroy_user_session_path, method: :delete, data: { "turbo-method": :delete }, class: "text-gray-800 font-medium hover:text-purple-500" %>
        </div>
      <% else %>
        <div class="flex space-x-4 md:space-x-6 items-center ml-auto">
          <%= link_to('Login', new_user_session_path, class: "text-gray-800 font-medium py-1 px-3 md:px-4 border border-gray-400 rounded shadow")  %>
          <%= link_to('Sign Up', new_user_registration_path, class: "text-gray-800 font-medium py-1 px-3 md:px-4 border border-gray-400 rounded shadow")  %>
        </div>
      <% end %>
    </div>
  </div>
    <!-- MOBILE MENU -->
  <div id="mobileMenu" class="hidden flex w-full mx-auto text-center">
    <div class="flex flex-col justify-center items-center w-full">
      <% if user_signed_in? %>
        <%= link_to 'Register Your Band', new_band_path, class: "block text-gray-900 cursor-pointer mt-1 py-3 transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500", style: "text-underline-offset: 8px;" %>
        <%= link_to 'Profile', user_path(current_user), class: "block text-gray-900 cursor-pointer mt-1 py-3 transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500", style: "text-underline-offset: 8px;" %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { "turbo-method": :delete }, class: "block text-gray-900 cursor-pointer mt-1 py-3 transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500", style: "text-underline-offset: 8px;"%>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "block text-gray-900 cursor-pointer mt-1 py-3 transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500", style: "text-underline-offset: 8px;"%>
          <%= link_to 'Sign Up', new_user_registration_path, class: "block text-gray-900 cursor-pointer mt-1 py-3 transition duration-300 focus:outline-none focus:text-yellow-500 focus:underline hover:underline hover:text-yellow-500", style: "text-underline-offset: 8px;"%>
      <% end %>
    </div>
  </div>
</nav>

<script>
// Gets the Mobile Nav icon by its ID
let bars = document.getElementById('bars');

// Gets the Mobile Nav container
let mobileMenu = document.getElementById('mobileMenu');

// Displays the Mobile Nav when clicked and changes the Nav Icon from three bars to an 'X'
bars.addEventListener('click', function(){
  mobileMenu.classList.toggle('hidden');
});
</script>

app/views/users/show.html.erb
<div class="md:w-2/5 mx-auto my-16 ">
  <h2 class="mb-8 font-semibold text-center"> My Profile </h2>
  <div class="p-8 bg-white shadow-md rounded space-y-4 my-4">
    <div class="space-y-1">
      <h3 class="font-normal text-base text-gray-700"> Name </h3>
      <p class="font-semibold text-base"><%= current_user.full_name %></p>
    </div>
    <hr>
    <div class="space-y-1">
      <h3 class="font-normal text-base text-gray-700"> Email </h3>
      <p class="font-semibold text-base"><%= current_user.email %></p>
    </div>
  </div>

  <div class="px-8 flex items-center justify-between content-end">
    <%= link_to "Edit Profile", edit_user_registration_path, class: "bg-purple-500 hover:bg-purple-700 text-white text-center font-bold w-full py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
</div>